
spring:
  application:
    name: sol-y-pago-gateway

  # Настройки подключения к базе данных PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/sol_y_pago_db
    username: admin
    password: admin # Укажите ваш пароль от PostgreSQL
    driver-class-name: org.postgresql.Driver

  # Настройки Hibernate/JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Автоматически создаст таблицы на основе @Entity (для демо это удобно)
    show-sql: true # Будет выводить все SQL-запросы в консоль для дебага
    properties:
      hibernate:
        format_sql: true

# Настройки встроенного сервера Tomcat
server:
  port: 8081

